version: "3"
services:
  postgressql:
    image: "postgres"
    container_name: "slack-db"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=messages
      - POSTGRES_ROOT_PASSWORD=test
    ports:
      - "5433:5432"
    volumes:
      - messages:/var/lib/postgresql/data
volumes:
  messages:
